vc_landmarks = {
  'Marine Building': {'Burrard', 'Waterfront'},
  'Scotiabank Field at Nat Bailey Stadium': {'King Edward'},
  'Vancouver Aquarium': {'Burrard'},
  'Vancouver Lookout': {'Waterfront'},
  'Canada Place': {'Burrard', 'Waterfront'},
  'Cathedral of Our Lady of the Holy Rosary': {'Vancouver City Centre', 'Granville'},
  'Library Square': {'Vancouver City Centre', 'Stadium-Chinatown'},
  'B.C. Place Stadium': {'Stadium-Chinatown'},
  'Lions Gate Bridge': {'Burrard'},
  'Gastown Steam Clock': {'Waterfront'},
  'Waterfront Station': {'Waterfront'},
  'Granville Street': {'Granville', 'Vancouver City Centre'},
  'Pacific Central Station': {'Main Street-Science World'},
  'Prospect Point Lighthouse': {'Burrard'},
  'Queen Elizabeth Theatre': {'Stadium-Chinatown'},
  'Stanley Park': {'Burrard'},
  'Granville Island Public Market': {'Yaletown-Roundhouse'},
  'Kitsilano Beach': {'Olympic Village'},
  'Dr. Sun Yat-Sen Classical Chinese Garden': {'Stadium-Chinatown'},
  'Museum of Vancouver': {'Yaletown-Roundhouse'},
  'Science World': {'Main Street-Science World'},
  'Robson Square': {'Vancouver City Centre'},
  'Samson V Maritime Museum': {'Columbia'},
  'Burnaby Lake': {'Sperling / Burnaby Lake', 'Lake City Way', 'Production Way / University'},
  'Nikkei National Museum & Cultural Centre': {'Edmonds'},
  'Central Park': {'Patterson', 'Metrotown'}
}