vc_metro = {
  'Richmond-Brighouse': {'Lansdowne'},
  'Lansdowne': {'Richmond-Brighouse', 'Aberdeen'},
  'Aberdeen': {'Lansdowne', 'Bridgeport'},
  'Bridgeport': {'Aberdeen', 'Templeton', 'Marine Drive'},
  'YVR-Airport': {'Sea Island Centre'},
  'Sea Island Centre': {'YVR-Airport', 'Templeton'},
  'Templeton': {'Sea Island Centre', 'Bridgeport'},
  'Marine Drive': {'Bridgeport', 'Langara-49th Avenue'},
  'Langara-49th Avenue': {'Marine Drive', 'Oakbridge-41st Avenue'},
  'Oakbridge-41st Avenue': {'Langara-49th Avenue', 'King Edward'},
  'King Edward': {'Oakbridge-41st Avenue', 'Broadway-City Hall'},
  'Broadway-City Hall': {'King Edward', 'Olympic Village'},
  'Olympic Village': {'Broadway-City Hall', 'Yaletown-Roundhouse'},
  'Yaletown-Roundhouse': {'Olympic Village', 'Vancouver City Centre'},
  'Vancouver City Centre': {'Yaletown-Roundhouse', 'Waterfront'},
  'Waterfront': {'Vancouver City Centre', 'Burrard'},
  'Burrard': {'Waterfront', 'Granville'},
  'Granville': {'Burrard', 'Stadium-Chinatown'},
  'Stadium-Chinatown': {'Granville', 'Main Street-Science World'},
  'Main Street-Science World': {'Stadium-Chinatown', 'Commercial-Broadway'},
  'Commercial-Broadway': {'VCC-Clark', 'Main Street-Science World', 'Renfrew', 'Nanaimo'},
  'VCC-Clark': {'Commercial-Broadway'},
  'Nanaimo': {'Commercial-Broadway', '29th Avenue'},
  '29th Avenue': {'Nanaimo', 'Joyce-Collingwood'},
  'Joyce-Collingwood': {'29th Avenue', 'Patterson'},
  'Patterson': {'Joyce-Collingwood', 'Metrotown'},
  'Metrotown': {'Patterson', 'Royal Oak'},
  'Royal Oak': {'Metrotown', 'Edmonds'},
  'Edmonds': {'Royal Oak', '22nd Street'},
  '22nd Street': {'Edmonds', 'New Westminster'},
  'New Westminster': {'22nd Street', 'Columbia'},
  'Columbia': {'New Westminster', 'Sapperton', 'Scott Road'},
  'Scott Road': {'Columbia', 'Gateway'},
  'Gateway': {'Scott Road', 'Surrey Central'},
  'Surrey Central': {'Gateway', 'King George'},
  'King George': {'Surrey Central'},
  'Sapperton': {'Columbia', 'Braid'},
  'Braid': {'Sapperton', 'Lougheed Town Centre'},
  'Lougheed Town Centre': {'Braid', 'Production Way / University', 'Burquitlam'},
  'Burquitlam': {'Lougheed Town Centre', 'Moody Centre'},
  'Moody Centre': {'Burquitlam', 'Inlet Centre'},
  'Inlet Centre': {'Moody Centre', 'Coquitlam Central'},
  'Coquitlam Central': {'Inlet Centre', 'Lincoln'},
  'Lincoln': {'Coquitlam Central', 'Lafarge Lake-Douglas'},
  'Lafarge Lake-Douglas': {'Lincoln'},
  'Production Way / University': {'Lougheed Town Centre', 'Lake City Way'},
  'Lake City Way': {'Production Way / University', 'Sperling / Burnaby Lake'},
  'Sperling / Burnaby Lake': {'Lake City Way', 'Holdom'},
  'Holdom': {'Sperling / Burnaby Lake', 'Brentwood Town Centre'},
  'Brentwood Town Centre': {'Holdom', 'Gilmore'},
  'Gilmore': {'Brentwood Town Centre', 'Rupert'},
  'Rupert': {'Gilmore', 'Renfrew'},
  'Renfrew': {'Rupert', 'Commercial-Broadway'}
  }